---
- hosts: all
  become: true
  tasks:

  - name: install apache2 package
    ansible.builtin.apt:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes
    when: ansible_distribution  == "ubuntu"



