---
- hosts: all
  become: true
  tasks:

  - name: update respository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution == "ubuntu"

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution  == "ubuntu"

  - name: install support fpr php
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "ubuntu"


